=== jpraet/sandbox/src/main/xsd/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://kszbcss.fgov.be/batch" xmlns:tns="http://kszbcss.fgov.be/batch" elementFormDefault="qualified">

    <element name="root" type="tns:RootType"></element>
    
    <element name="master" type="tns:MasterType"></element>
    
    <element name="detail" type="tns:DetailType"></element>
    
    <complexType name="RootType">
     <sequence>
      <element name="header" type="string"></element>
      <element name="masters" type="tns:MastersType" maxOccurs="1" minOccurs="0"></element>
     </sequence>
    </complexType>
    
    <complexType name="MasterType">
     <sequence>
      <element name="value" type="string"></element>
      <element name="details" type="tns:DetailsType" maxOccurs="1" minOccurs="0"></element>
     </sequence>
    </complexType>
    
    <complexType name="DetailsType">
     <sequence>
      <element name="detail" type="tns:DetailType" maxOccurs="unbounded" minOccurs="1"></element>
     </sequence>
    </complexType>
    
    <complexType name="DetailType">
     <sequence>
      <element name="value" type="string"></element>
     </sequence>
    </complexType>

    <complexType name="MastersType">
     <sequence>
      <element name="master" type="tns:MasterType" maxOccurs="unbounded" minOccurs="1"></element>
     </sequence>
    </complexType>
    
</schema>

=== jpraet/sandbox/src/test/resources/master-detail.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:root xmlns:tns="http://kszbcss.fgov.be/batch" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://kszbcss.fgov.be/batch ../../main/xsd/schema.xsd ">
  <tns:header>header</tns:header>
  <tns:masters>
    <tns:master>
      <tns:value>master-1</tns:value>
      <tns:details>
        <tns:detail>
          <tns:value>detail-1.1</tns:value>
        </tns:detail>
        <tns:detail>
          <tns:value>detail-1.2</tns:value>
        </tns:detail>
      </tns:details>
    </tns:master>
    <tns:master>
      <tns:value>master-2</tns:value>
      <tns:details>
        <tns:detail>
          <tns:value>detail-2.1</tns:value>
        </tns:detail>
      </tns:details>
    </tns:master>
    <tns:master>
      <tns:value>master-3</tns:value>
    </tns:master>
    <tns:master>
      <tns:value>master-4</tns:value>
      <tns:details>
        <tns:detail>
          <tns:value>detail-4.1</tns:value>
        </tns:detail>
        <tns:detail>
          <tns:value>detail-4.2</tns:value>
        </tns:detail>
        <tns:detail>
          <tns:value>detail-4.3</tns:value>
        </tns:detail>
      </tns:details>
    </tns:master>
  </tns:masters>
</tns:root>
